### ISSUE TITLE
双击exe后报错

### ISSUE THREAD

**Issue by lucky9805** [ImGoodBai/GoodWeBot#2]
Traceback (most recent call last):
  File "server-ui.py", line 23, in <module>
NameError: name 'exit' is not defined

win10 64位

要先动微信客户端登录再运行。

**Comment by ImGoodBai** [comment]
> Traceback (most recent call last): File "server-ui.py", line 23, in NameError: name 'exit' is not defined
> 
> win10 64位
> 
> 要先动微信客户端登录再运行。

要先动微信客户端登录再运行。

**Comment by chudog26** [comment]
好吧，我的win11，哭了，
